### ISSUE TITLE
[Company] List All Companies

### ISSUE THREAD

**Issue by caiodias** [ProDigi-Developement/Web-Advanced-Course-Project#14]
To Do:
 - [x] Create the fetch all Companies on API layer.
 - [x] Create the method on Controller layer.

**Comment by bmarchete** [comment]
@caiodias Whenever you can, give some feedback. Thanks.

**Comment by caiodias** [comment]
Solved on PR: https://github.com/ProDigi-Developement/Web-Advanced-Course-Project/pull/27

**Comment by caiodias** [comment]
Reopening due to request from João
