### ISSUE TITLE
Code guidelines

### ISSUE THREAD

**Issue by bmarchete** [ProDigi-Developement/Web-Advanced-Course-Project#7]
I'm suggesting to follow some code guidelines to keep the source code standardized.

- Use [Strict Mode](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Strict_mode) since we are not handling with transpilers such as babel
- Use [eslint](https://eslint.org/) as the standard javascript linter. It helps to keep the code organized, formatting and presenting errors during the coding process, like
  - code ident standard
  - quotes style
  - are we using semi columns?
- Use [javascript code document](http://usejsdoc.org/) to expose classes and methods documentation

We can discuss those ideas and how to set everything up during classes! 🎉

**Comment by caiodias** [comment]
I agree, please instruct your team to follow it.

Can you please create a readme.md file with these instructions? 🙂

**Comment by bmarchete** [comment]
The README.md is done 🎉
